fastlane_version "2.27.0"

default_platform :ios

lane :test do
  cocoapods(
  	repo_update: true
  )

  scan(
    scheme: "SKWebServiceController",
    workspace: "SKWebServiceController.xcworkspace"
  )
end
